const languages = {
    en: {
        menu: {
            start_game: "Start Game",
            exit_game: "Exit Game",
            language_option: "Switch Language",
            select_language: "Select Language",
            english: "English",
            norwegian: "Norwegian",
            back: "Back",
        },
        splash: "Battleships",
        ship_placement_phase: "Ship Placement Phase",
        controls: "Controls:",
        arrow_keys: "Arrow keys: Move cursor",
        r_rotate: "R: Rotate ship",
        enter_place_ship: "Enter: Place ship",
        ships_to_place: "Ships to place:",
        hit: "Hit!",
        miss: "Miss!",
        already_fired: "You already fired at this location.",
        press_enter_to_continue: "Press Enter to continue...",
        enter_fire: "Enter: Fire",
        game_over: "Game Over!",
        player_wins: "Player {player} wins!",
        play_again: "Play Again",
        exit: "Exit Game",
        player_turn: "Player {player}'s Turn",
        ship_placement_instructions: "SHIP PLACEMENT\n{player} get ready.\n{other_player} look away",
        resize_message: "Please resize your console window to at least {columns} columns and {rows} rows.",
    },
    no: {
        menu: {
            start_game: "Start Spill",
            exit_game: "Avslutt Spill",
            language_option: "Bytt Språk",
            select_language: "Velg Språk",
            english: "Engelsk",
            norwegian: "Norsk",
            back: "Tilbake",
        },
        splash: "Sjøslag",
        ship_placement_phase: "Skipplasseringsfase",
        controls: "Kontroller:",
        arrow_keys: "Piltaster: Flytt markør",
        r_rotate: "R: Roter skip",
        enter_place_ship: "Enter: Plasser skip",
        ships_to_place: "Skip å plassere:",
        hit: "Treff!",
        miss: "Bom!",
        already_fired: "Du har allerede skutt på denne posisjonen.",
        press_enter_to_continue: "Trykk Enter for å fortsette...",
        enter_fire: "Enter: Skyt",
        game_over: "Spillet er over!",
        player_wins: "Spiller {player} vinner!",
        play_again: "Spill Igjen",
        exit: "Avslutt Spill",
        player_turn: "Spiller {player} sin tur",
        ship_placement_instructions: "SKIPPLASSERING\n{player} gjør deg klar.\n{other_player} se bort",
        resize_message: "Vennligst endre størrelse på konsollvinduet til minst {columns} kolonner og {rows} rader.",
    }
}

export default languages;
